version: "3.9"

services:
  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - my-db:/var/lib/mysql
      - "./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    environment:
      MYSQL_DATABASE: 'books'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3306'

  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

  backend:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    depends_on:
      - mysql_db
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      MYSQL_DATABASE: books
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234

  frontend:
    stdin_open: true
    tty: true
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8000:8080
    depends_on:
      - mysql_db
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db

volumes:
  my-db: